### ISSUE TITLE
when multiple web server and use redis store session. the session is not sync.

### ISSUE THREAD

**Issue by eosite** [kataras/go-sessions#12]
when multiple web server and use redis store session. the session is not sync.

**Comment by imkos** [comment]
yes, not share! it use  sync.RWMutex + map[string]interface{} . redis is Backup

**Comment by imkos** [comment]
this is my code:
```go
 var _ iris.Session = &session{}
 
+var OnlyUseDBStoreSessionInfo bool
+
 // ID returns the session's id
 func (s *session) ID() string {
 	return s.sid
 }
 
 // Get returns the value of an entry by its key
 func (s *session) Get(key string) interface{} {
 	s.mu.RLock()
+	if OnlyUseDBStoreSessionInfo || len(s.provider.databases) > 0 {
+		s.values = s.provider.databases[0].Load(s.sid)
+	}
 	value := s.values[key]
 	s.mu.RUnlock()
 
 	return value
 }
```

**Comment by kataras** [comment]
Unlike other sessions managers, this session manager doesn't calling the database directly, for performance and scalability reasons. Database can `Load` values to the sessions store and session store can call database's `Update`(Save or Remove) to update a database value, as described [here](https://github.com/kataras/go-sessions/blob/master/database.go#L15).

**Comment by kataras** [comment]
Unlike other session managers, this session manager doesn't call the database directly, for performance and scalability reasons (multiple machines, sharing a database). Database can `Load` values to the sessions store and session store can call database's `Update`(Save or Remove) to update a database value, as described [here](https://github.com/kataras/go-sessions/blob/master/database.go#L15).

**Comment by eosite** [comment]
thx
