### ISSUE TITLE
Why is there no GcDuration parameter?

### ISSUE THREAD

**Issue by dxvgef** [kataras/go-sessions#13]
I see the GcDuration parameters in the Iris session, but in the go-session package why not see this parameter and related functions?

**Comment by kataras** [comment]
There is no need for that anymore, the new session manager, version 2.0.0 handles this automatically.

**More on version 2.0.0**

- [Overview](_examples/overview/main.go)
- [Standalone](_examples/standalone/main.go)
- [Fasthttp](_examples/fasthttp/main.go)
- [Secure Cookie](_examples/securecookie/main.go)
- [Flash Messages](_examples/flash-messages/main.go)
- [Databases](_examples/database)
	* [File](_examples/database/file/main.go)
	* [BoltDB](_examples/database/boltdb/main.go)
	* [LevelDB](_examples/database/leveldb/main.go)
	* [Redis](_examples/database/redis/main.go)
