### ISSUE TITLE
use redis and restart server

### ISSUE THREAD

**Issue by morolt** [kataras/go-sessions#16]
[ERRO] 2017/09/30 13:26 error while trying to load session values(1027f009-8996-47b0-bb21-fd090e07c265) from redis:
		the retrieved value is not a sessions.RemoteStore type, please report that as bug, it should never occur

**Comment by morolt** [comment]
I changed sessionid ttl
127.0.0.1:6379[9]> ttl 1027f009-8996-47b0-bb21-fd090e07c265
(integer) 2590918
127.0.0.1:6379[9]> get 1027f009-8996-47b0-bb21-fd090e07c265
"3\xff\x81\x03\x01\x01\x0bRemoteStore\x01\xff\x82\x00\x01\x02\x01\x06Values\x01\xff\x86\x00\x01\bLifetime\x01\xff\x88\x00\x00\x00\x14\xff\x85\x02\x01\x01\x05Store\x01\xff\x86\x00\x01\xff\x84\x00\x00(\xff\x83\x03\x01\x01\x05Entry\x01\xff\x84\x00\x01\x02\x01\x03Key\x01\x0c\x00\x01\bValueRaw\x01\x10\x00\x00\x00\x14\xff\x87\x05\x01\x01\bLifeTime\x01\xff\x88\x00\x00\x00\x10\xff\x89\x05\x01\x01\x04Time\x01\xff\x8a\x00\x00\x00(\xff\x82\x01\x01\x01\x04test\x01\x03int\x04\x04\x00\xfe\xdf\x0c\x00\x01\x0f\x01\x00\x00\x00\x0e\xd1\x88\xab\xc7\x1a'~\xe0\x01\xe0\x00"

**Comment by kataras** [comment]
@morolt Hello, I pushed the next version. Upgrade with `go get -u github.com/kataras/go-sessions` and try again please, it should be fixed, tell us the results
