### ISSUE TITLE
Only set cookie if there is a session?

### ISSUE THREAD

**Issue by bluedaniel** [kataras/go-sessions#5]
Hi, is there any way of setting the cookie to be set on the browser manually rather than with every request?

ie only if there is a value in session or once a route is requested?

Thanks

**Comment by kataras** [comment]
I don't understand, that's the way of sessions, maybe you do something wrong or you confused this with other library?

**Comment by bluedaniel** [comment]
I would have preferred storing a session only for authenticated users for example.

It doesn't matter too much really.

**Comment by kataras** [comment]
This is up to you my friend, this library gives you the freedom to decide when and where to use sessions
