### ISSUE TITLE
BoltDB support

### ISSUE THREAD

**Issue by avbru** [kataras/go-sessions#8]
Add BoltDB support

**Comment by zyfdegh** [comment]
+1

**Comment by lexesv** [comment]
+1

**Comment by kataras** [comment]
Done, example can be found there: 
https://github.com/kataras/go-sessions/tree/master/_examples/database/boltdb

**More on version 2.0.0**

- [Overview](_examples/overview/main.go)
- [Standalone](_examples/standalone/main.go)
- [Fasthttp](_examples/fasthttp/main.go)
- [Secure Cookie](_examples/securecookie/main.go)
- [Flash Messages](_examples/flash-messages/main.go)
- [Databases](_examples/database)
	* [File](_examples/database/file/main.go)
	* [BoltDB](_examples/database/boltdb/main.go)
	* [LevelDB](_examples/database/leveldb/main.go)
	* [Redis](_examples/database/redis/main.go)
